name: "Release Plugin"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '8.16.1'

jobs:
  release_plugin:
    name: Release Plugin
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        repository: elastic/kibana
        ref: refs/heads/main

    - uses: actions/checkout@v4
      with:
        name: lht-poc/platform-monitoring-kibana-prometheus-exporter
        ref: refs/heads/main
        path: 'plugins/kibana-prometheus-exporter'

    - name: Install workflow dependencies
      run: sudo apt-get install -y jq

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Set up Kibana Development Environment
      run: yarn kbn bootstrap
      
    - name: Build plugin
      working-directory: plugins/kibana-prometheus-exporter
      run: echo "${{ github.event.inputs.version }}" | yarn build
    
    - name: Create checksum manifest
      working-directory: plugins/kibana-prometheus-exporter/build
      run: ../utils/checksum ./*.zip >checksum.json

    - name: Update and copy RELEASE_TEMPLATE.md
      working-directory: plugins/kibana-prometheus-exporter
      run: sed "s/VERSION/${{ github.event.inputs.version }}/g" ./utils/RELEASE_TEMPLATE.md > ./build/RELEASE_TEMPLATE.md

    - name: Sanity Check
      working-directory: plugins/kibana-prometheus-exporter/build
      run: ls -la && cat RELEASE_TEMPLATE.md

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ github.event.inputs.version }}"
        release_name: "${{ github.event.inputs.version }}"
        body_path: plugins/kibana-prometheus-exporter/build/RELEASE_TEMPLATE.md
        draft: false
        prerelease: false

    - name: Upload release artifact (Kibana Plugin)
      id: upload-release-asset-plugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: plugins/kibana-prometheus-exporter/build/kibanaPrometheusExporter-${{ github.event.inputs.version }}.zip
        asset_name: kibanaPrometheusExporter-${{ github.event.inputs.version }}.zip
        asset_content_type: application/zip

    - name: Upload release artifact (Checksum manifest)
      id: upload-release-asset-checksum-manifest
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: plugins/kibana-prometheus-exporter/build/checksum.json
        asset_name: checksum.json
        asset_content_type: application/json
